### ISSUE TITLE
Im getting this error

### ISSUE THREAD

**Issue by TheScriptShowcaser** [CodeWithSwastik/overlord-gpt#1]
~/overlord-gpt $ python main.py
/data/data/com.termux/files/usr/lib/python3.11/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
2024-01-15 00:40:46 INFO     discord.client logging in using static token
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/overlord-gpt/main.py", line 340, in <module>
    client.run(os.getenv('replaced cuz I wont leak the token'))
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/discord/client.py", line 849, in runner
    await self.start(token, reconnect=reconnect)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/discord/client.py", line 777, in start
    await self.login(token)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/discord/client.py", line 609, in login
    raise TypeError(f'expected token to be a str, received {token.__class__.__name__} instead')
TypeError: expected token to be a str, received NoneType instead

**Comment by CodeWithSwastik** [comment]
You need to set the bot token in a file called .env
